--------------------------------------------------------
--  DDL for View AAD_CUENTA_ICEBERG_GRUPO
--------------------------------------------------------

  CREATE OR REPLACE FORCE VIEW "ICEBERG_PRE"."AAD_CUENTA_ICEBERG_GRUPO" ("SEC_CUENTA_ICEBERG_GRUPO", "SEC_CUENTA_ICEBERG", "SEC_GRUPO_ICEBERG", "SEC_ROL_ICEBERG", "ESTADO", "DESCRIPCION") AS 
  SELECT 
	CIG.SEC_CUENTA_ICEBERG_GRUPO,
	CIG.SEC_CUENTA_ICEBERG,
	CIG.SEC_GRUPO_ICEBERG,
	CIG.SEC_ROL_ICEBERG,
	CIG.ESTADO,
	CIG.DESCRIPCION
FROM AAT_CUENTA_ICEBERG_GRUPO CIG
 ;
