--------------------------------------------------------
--  DDL for View AAD_CUENTA_ICEBERG
--------------------------------------------------------

  CREATE OR REPLACE FORCE VIEW "ICEBERG_PRE"."AAD_CUENTA_ICEBERG" ("SEC_CUENTA_ICEBERG", "SEC_PERSONA", "CUENTA_ICEBERG", "ESTADO", "COPIA_CORREO_ALTERNO", "OBLIGA_CAMBIO_CLAVE", "VENCIMIENTO_CLAVE", "FECHA_CREACION", "FECHA_ULTIMO_CAMBIO_CLAVE", "FECHA_AUTENTICACION_EXITOSA", "NUMERO_INGRESOS_FALLIDOS", "FECHA_REACTIVACION", "FECHA_VENCIMIENTO", "CLAVE", "LDAP_DN", "SEC_GRUPO_ICEBERG", "SEC_IDIOMA", "SEC_REGION", "APARIENCIA_ICEBERG", "NIVEL_LOG", "DESCRIPCION") AS 
  SELECT 
  CIC.SEC_CUENTA_ICEBERG,
  CIC.SEC_PERSONA,
  CIC.CUENTA_ICEBERG,
  CIC.ESTADO,
  CIC.COPIA_CORREO_ALTERNO,
  CIC.OBLIGA_CAMBIO_CLAVE,
  CIC.VENCIMIENTO_CLAVE,
  CIC.FECHA_CREACION,
  CIC.FECHA_ULTIMO_CAMBIO_CLAVE,
  CIC.FECHA_AUTENTICACION_EXITOSA,
  CIC.NUMERO_INGRESOS_FALLIDOS,
  CIC.FECHA_REACTIVACION,
  CIC.FECHA_VENCIMIENTO,
  CIC.CLAVE,
  CIC.LDAP_DN,
  CIC.SEC_GRUPO_ICEBERG,
  CIC.SEC_IDIOMA,
  CIC.SEC_REGION,
  CIC.APARIENCIA_ICEBERG,
  CIL.NIVEL_LOG,
  CIC.DESCRIPCION
FROM AAT_CUENTA_ICEBERG CIC
  LEFT OUTER JOIN AAT_CUENTA_ICEBERG_LOGGING CIL
    ON CIL.SEC_CUENTA_ICEBERG = CIC.SEC_CUENTA_ICEBERG
 ;
