--------------------------------------------------------
--  DDL for Table AAT_AUDITORIA
--------------------------------------------------------

  CREATE TABLE "ICEBERG_PRE"."AAT_AUDITORIA" 
   (	"SEC_AUDITORIA" NUMBER(12,0), 
	"INSTANTE" DATE, 
	"TABLA" VARCHAR2(30 BYTE), 
	"SEC_REGISTRO" NUMBER(12,0), 
	"OPERACION" CHAR(1 BYTE), 
	"SEC_CUENTA_ICEBERG" NUMBER(12,0), 
	"SEC_EJECUTABLE" NUMBER(12,0), 
	"REGISTRO_ANTERIOR" "SYS"."XMLTYPE" , 
	"REGISTRO_NUEVO" "SYS"."XMLTYPE" 
   ) PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 NOCOMPRESS LOGGING
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT)
  TABLESPACE "DATOS" 
 XMLTYPE COLUMN "REGISTRO_ANTERIOR" STORE AS CLOB (
  TABLESPACE "BINARIOS" ENABLE STORAGE IN ROW CHUNK 8192 PCTVERSION 10
  NOCACHE LOGGING 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT)) 
 XMLTYPE COLUMN "REGISTRO_NUEVO" STORE AS CLOB (
  TABLESPACE "BINARIOS" ENABLE STORAGE IN ROW CHUNK 8192 PCTVERSION 10
  NOCACHE LOGGING 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT)) ;
 

   COMMENT ON COLUMN "ICEBERG_PRE"."AAT_AUDITORIA"."SEC_AUDITORIA" IS 'Secuencia del registro - Llave primaria sustituta';
 
   COMMENT ON COLUMN "ICEBERG_PRE"."AAT_AUDITORIA"."INSTANTE" IS 'Instante del Evento';
 
   COMMENT ON COLUMN "ICEBERG_PRE"."AAT_AUDITORIA"."TABLA" IS 'Nombre de la tabla que se altera';
 
   COMMENT ON COLUMN "ICEBERG_PRE"."AAT_AUDITORIA"."SEC_REGISTRO" IS 'Secuencia del Registro alterado. (Llave primaria sustituta)';
 
   COMMENT ON COLUMN "ICEBERG_PRE"."AAT_AUDITORIA"."OPERACION" IS 'Tipo de Operación DML realizado al registro:  (N)uevo,  (A)ctualizado, (E)liminado';
 
   COMMENT ON COLUMN "ICEBERG_PRE"."AAT_AUDITORIA"."SEC_CUENTA_ICEBERG" IS 'Secuencia de la Cuenta ICEBERG que genera el cambio';
 
   COMMENT ON COLUMN "ICEBERG_PRE"."AAT_AUDITORIA"."SEC_EJECUTABLE" IS 'Secuencia del Ejecutable que se audita';
 
   COMMENT ON COLUMN "ICEBERG_PRE"."AAT_AUDITORIA"."REGISTRO_ANTERIOR" IS 'Registro anterior antes de aplicar DML. Aplica para Modificado y Eliminado';
 
   COMMENT ON COLUMN "ICEBERG_PRE"."AAT_AUDITORIA"."REGISTRO_NUEVO" IS 'Registro nuevo posterior a DML. Aplica para Nuevo y Modificado';
 
   COMMENT ON TABLE "ICEBERG_PRE"."AAT_AUDITORIA"  IS 'Registro de Auditoría de cambios en las Tablas realizados por los ejecutables ICEBERG';
